packages:
  - "."

allowBuilds:
  "@firebase/util": true
  protobufjs: true
  "@ffmpeg-installer/ffmpeg": true
  "@ffmpeg-installer/linux-x64": true
  "@ffmpeg-installer/linux-arm64": true
  "@ffmpeg-installer/darwin-x64": true
  "@ffmpeg-installer/darwin-arm64": true
