/**
 * SVC Directory — Files.
 *
 * Files are a SEPARATE collection linked to entities by composite id in
 * `entityIds` — never stored as a giant array inside a contact/context. Each
 * doc records the Storage path + a public download URL plus light metadata.
 * `category` supports lightweight classification such as reports generated by
 * the three-week outlook flow; ordinary uploads still default to "general".
 *
 * Global-readable, owner-scoped writes. The binary lives in Firebase Storage
 * under the uploader-owned `directory-files/{uid}/…` prefix. Authenticated
 * users may read it and the stored token URL supports PDF sharing/message links.
 */

import {
  addDoc,
  collection,
  deleteDoc,
  doc,
  documentId,
  getDocs,
  limit,
  orderBy,
  query,
  serverTimestamp,
  startAfter,
  Timestamp,
  where,
  type Unsubscribe,
} from "firebase/firestore"
import { db, getStorageLazy } from "@/lib/firebase"
import { subscribeWithServerReconcile } from "@/lib/firestore-reconcile"

/** Uploads default to "general"; feature-specific flows may select a category. */
export type DirectoryFileCategory =
  | "general"
  | "photo"
  | "report"
  | "issue"
  | "plan"
  | "safety"
  | "profile"

export interface DirectoryFile {
  id: string
  entityIds: string[]
  storagePath: string
  downloadUrl: string
  fileName: string
  mimeType: string
  size: number
  category: DirectoryFileCategory
  caption: string
  uploadedBy: string
  createdAt: Date | null
}

export interface DirectoryFilesPage {
  items: DirectoryFile[]
  hasMore: boolean
}

export const MAX_DIRECTORY_FILE_BYTES = 15 * 1024 * 1024 // 15 MB

const FILES = "directoryFiles"

function toDate(value: unknown): Date | null {
  if (value && typeof value === "object" && "toDate" in value && typeof (value as { toDate: unknown }).toDate === "function") {
    return (value as { toDate: () => Date }).toDate()
  }
  return null
}

function mapFile(id: string, data: Record<string, unknown>): DirectoryFile {
  return {
    id,
    entityIds: Array.isArray(data.entityIds) ? data.entityIds.filter((v): v is string => typeof v === "string") : [],
    storagePath: typeof data.storagePath === "string" ? data.storagePath : "",
    downloadUrl: typeof data.downloadUrl === "string" ? data.downloadUrl : "",
    fileName: typeof data.fileName === "string" ? data.fileName : "file",
    mimeType: typeof data.mimeType === "string" ? data.mimeType : "application/octet-stream",
    size: typeof data.size === "number" ? data.size : 0,
    category: (typeof data.category === "string" ? data.category : "general") as DirectoryFileCategory,
    caption: typeof data.caption === "string" ? data.caption : "",
    uploadedBy: typeof data.uploadedBy === "string" ? data.uploadedBy : "",
    createdAt: toDate(data.createdAt),
  }
}

export function isImageFile(file: Pick<DirectoryFile, "mimeType">): boolean {
  return file.mimeType.startsWith("image/")
}

const FILES_PAGE_SIZE = 50

function filesQueryFor(directoryId: string) {
  return query(
    collection(db, FILES),
    where("entityIds", "array-contains", directoryId),
    orderBy("createdAt", "desc"),
    orderBy(documentId(), "desc"),
  )
}

function sanitizeStorageName(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]+/g, "_").replace(/_{2,}/g, "_").slice(0, 120) || "file"
}

/** Live first page for one entity; older pages are fetched on demand. */
export function subscribeDirectoryFiles(
  directoryId: string,
  onChange: (files: DirectoryFile[]) => void,
  onError?: (error: Error) => void,
): Unsubscribe {
  const filesQuery = query(filesQueryFor(directoryId), limit(FILES_PAGE_SIZE))
  return subscribeWithServerReconcile(
    filesQuery,
    (snapshot) => {
      onChange(snapshot.docs.map((entry) => mapFile(entry.id, entry.data())))
    },
    (error) => onError?.(error),
  )
}

export async function loadDirectoryFilesPage(
  directoryId: string,
  cursor: { createdAt: Date; id: string },
): Promise<DirectoryFilesPage> {
  const snapshot = await getDocs(query(
    filesQueryFor(directoryId),
    startAfter(Timestamp.fromDate(cursor.createdAt), cursor.id),
    limit(FILES_PAGE_SIZE),
  ))
  return {
    items: snapshot.docs.map((entry) => mapFile(entry.id, entry.data())),
    hasMore: snapshot.size === FILES_PAGE_SIZE,
  }
}

export interface UploadFileOptions {
  category?: DirectoryFileCategory
  caption?: string
  additionalEntityIds?: string[]
}

export async function uploadDirectoryFile(
  userId: string,
  directoryId: string,
  file: File,
  options: UploadFileOptions = {},
): Promise<DirectoryFile> {
  if (file.size > MAX_DIRECTORY_FILE_BYTES) {
    throw new Error(`File is too large (max ${Math.round(MAX_DIRECTORY_FILE_BYTES / (1024 * 1024))} MB).`)
  }
  let payload: File = file
  // Compress images the same way message images are handled.
  if (file.type.startsWith("image/")) {
    try {
      const { compressImageFile } = await import("@/lib/image-upload")
      payload = await compressImageFile(file)
    } catch {
      payload = file
    }
  }

  const { ref, uploadBytes, getDownloadURL } = await import("firebase/storage")
  const storage = await getStorageLazy()
  const safeName = sanitizeStorageName(payload.name || file.name)
  const storagePath = `directory-files/${userId}/${Date.now()}-${safeName}`
  const storageRef = ref(storage, storagePath)
  const contentType = payload.type || file.type || "application/octet-stream"
  await uploadBytes(storageRef, payload, { contentType })
  const downloadUrl = await getDownloadURL(storageRef)

  const entityIds = [...new Set([directoryId, ...(options.additionalEntityIds ?? [])])].filter(Boolean)
  const created = await addDoc(collection(db, FILES), {
    entityIds,
    storagePath,
    downloadUrl,
    fileName: file.name,
    mimeType: contentType,
    size: payload.size,
    category: options.category ?? "general",
    caption: options.caption ?? "",
    uploadedBy: userId,
    createdAt: serverTimestamp(),
  })
  return {
    id: created.id,
    entityIds,
    storagePath,
    downloadUrl,
    fileName: file.name,
    mimeType: contentType,
    size: payload.size,
    category: options.category ?? "general",
    caption: options.caption ?? "",
    uploadedBy: userId,
    createdAt: null,
  }
}

export async function deleteDirectoryFile(file: DirectoryFile): Promise<void> {
  // Delete the Firestore doc first (owner-scoped rule); best-effort remove the blob.
  await deleteDoc(doc(db, FILES, file.id))
  if (file.storagePath) {
    try {
      const { ref, deleteObject } = await import("firebase/storage")
      const storage = await getStorageLazy()
      await deleteObject(ref(storage, file.storagePath))
    } catch {
      // Blob may already be gone or rules may forbid delete — the doc is what the UI reads.
    }
  }
}
